name: faster_rcnn
# trainer
devices: [0,1]
# devices: [0]
val_check_interval: 1
check_val_every_n_epoch: 1
accumulate_grad_batches: 1
# log_every_n_steps: 200
log_every_n_steps: 1
flush_logs_every_n_steps: 1
refresh_rate: 10
# model
model:
  num_classes: 2
  hidden_layer: 256

# hyperparams
max_epochs: 30
train:
  batch_size: 2
  optimizer:
    name: sgd
    params:
      lr: 0.00001
      weight_decay: 0.0005
      momentum: 0.9
  lr_scheduler: 
    name: step
    params:
      step_size: 10
      gamma: 0.1
  warmup: False
val:
  batch_size: 2

# dataset
num_workers: 4
split:
  # train: ['MOT17-02', 'MOT17-04', 'MOT17-05', 'MOT17-10', 'MOT17-11', 'MOT17-13']
  train: ['MOT17-09']
  val: ['MOT17-09']
  test: ['MOT17-09']
# loggers
wandb: True
# tb: True
# wandb: False
tb: False
# csv: True

# callbacks
checkpoints:
  every_n_epochs: 2
  mintor: train/epoch/loss
# device_stats_monitor: True
# early_stopping:
#   monitor: val/epoch/loss
#   patience: 3
# model_summary:
#   max_path: 1

# debug
fast_dev_run: False
# fast_dev_run: True
profiler: null
# overfit_batches: 10
# num_sanity_val_steps: 2

# reproducibility
deterministic: False
benchmark: False