name: mask_rcnn
# trainer
# devices: [0,1]
devices: [0]
val_check_interval: 1.0
check_val_every_n_epoch: 1
accumulate_grad_batches: 1

# model
model:
  num_classes: 2
  hidden_layer: 256

# hyperparams
max_epochs: 10
train:
  batch_size: 2
  optim:
    optimizer: sgd
    scheduler: step
    lr: 0.005
    momentum: 0.9
    step_size: 3
    weight_decay: 0.0005
    gamma: 0.1
val:
  batch_size: 1

# dataset
num_workers: 4
# loggers
wandb: True
tb: True
# csv: True

# callbacks
checkpoints:
  every_n_epochs: 1
  mintor: train/epoch/loss
# device_stats_monitor: True
# early_stopping:
#   monitor: val/epoch/loss
#   patience: 3
# model_summary:
#   max_path: 1

# debug
fast_dev_run: False
# fast_dev_run: True
profiler: null
overfit_batches: 0
# num_sanity_val_steps: 2
num_sanity_val_steps: 0

# reproducibility
deterministic: False
benchmark: False