name: tests

on:
  push:
    branches:
      - main
      - dev/*

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      # setup python
      - name: Set up python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          auto-update-conda: true
          python-version: "3.9"
          activate-environment: true
          miniconda-version: 'latest'
      
      # checkout to the repo
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: test commands
        run : |
          which conda
          which python
          python --version
          conda --version
      
      # create env and install packages
      - name: Create environment and install packages
        run: |
          echo "Setting conda init..."
          CONDA_PATH=$(conda info | grep -i 'base environment' | cut -d ":" -f2 | cut -d " " -f2)
          source $CONDA_PATH/etc/profile.d/conda.sh
          ./dev_install.sh
      
      # run tests
      - name: Run tests
        run: |
          echo "Setting conda init..."
          CONDA_PATH=$(conda info | grep -i 'base environment' | cut -d ":" -f2 | cut -d " " -f2)
          source $CONDA_PATH/etc/profile.d/conda.sh
          echo "Activating environment..."
          conda activate pl_jdt
          python -m pytest tests
      
      # - name: Upload coverage
      #   uses: codecov/codecov-action@v1.5.0
      #   with:
      #     flags: integration
      #     env_vars: OS,PYTHON,TORCH